name: hotspot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - ipykernel
  - altair-all
  - dash
  - dash-bootstrap-components
  - plotly
  - pip=24.0
  - pip:
      - dash-vega-components
      - flask-caching
